[project_definition]
binary_path = "./a2"
makefile_path = "."
make_targets = ["all"]
project_name = "a2"
global_timeout = 120

################################################################################
## M1 public test cases
##
[[testcases]]
name = "M1 Start (Example Output)"
description = "Example output from description of M1"
type = "OrdIO"
io_file = "tests/01/io.txt"
io_prompt = "s*>\\s*$"
exp_exit_code = 0
argv = ["configs/dungeon_config_01.txt", "configs/story_config.txt"]
protected = false
env_vars = ['RAND_SEED=1234']

[[testcases]]
name = "Wrong Dungeon Config"
description = "Wrong Magic Word in dungeon config"
type = "OrdIO"
io_file = "tests/02/io.txt"
io_prompt = "s*>\\s*$"
exp_exit_code = 3
argv = ["configs/dungeon_config_02.txt", "configs/story_config.txt"]
protected = false
env_vars = ['RAND_SEED=1234']

[[testcases]]
name = "Wrong Parameters"
description = ""
type = "OrdIO"
io_file = "tests/03/io.txt"
io_prompt = "s*>\\s*$"
exp_exit_code = 2
argv = ["configs/dungeon_config_03.txt"]
protected = false
env_vars = ['RAND_SEED=1234']

[[testcases]]
name = "Big Dungeon Room"
description = ""
type = "OrdIO"
io_file = "tests/04/io.txt"
io_prompt = "s*>\\s*$"
exp_exit_code = 0
argv = ["configs/dungeon_config_04.txt", "configs/story_config.txt"]
protected = false
env_vars = ['RAND_SEED=1234']

################################################################################
## M2 public test cases
##
[[testcases]]
name = "M2 Full Game"
description = "Sample output from M2 description"
type = "OrdIO"
io_file = "tests/05/io.txt"
io_prompt = "s*>\\s*$"
exp_exit_code = 0
argv = ["configs/dungeon_config_05.txt", "configs/story_config.txt"]
protected = false
env_vars = ['RAND_SEED=1234']
add_exp_file = "tests/05/save_ref.txt"
add_out_file = "saves/save_05.txt"

[[testcases]]
name = "help command"
description = ""
type = "OrdIO"
io_file = "tests/06/io.txt"
io_prompt = "s*>\\s*$"
exp_exit_code = 0
argv = ["configs/dungeon_config_06.txt", "configs/story_config.txt"]
protected = false
env_vars = ['RAND_SEED=1234']

[[testcases]]
name = "story command"
description = ""
type = "OrdIO"
io_file = "tests/07/io.txt"
io_prompt = "s*>\\s*$"
exp_exit_code = 0
argv = ["configs/dungeon_config_07.txt", "configs/story_config.txt"]
protected = false
env_vars = ['RAND_SEED=879212495']

[[testcases]]
name = "map command"
description = ""
type = "OrdIO"
io_file = "tests/08/io.txt"
io_prompt = "s*>\\s*$"
exp_exit_code = 0
argv = ["configs/dungeon_config_08.txt", "configs/story_config.txt"]
protected = false
env_vars = ['RAND_SEED=879212495']

[[testcases]]
name = "positions command"
description = ""
type = "OrdIO"
io_file = "tests/09/io.txt"
io_prompt = "s*>\\s*$"
exp_exit_code = 0
argv = ["configs/dungeon_config_09.txt", "configs/story_config.txt"]
protected = false
env_vars = ['RAND_SEED=1234']

[[testcases]]
name = "player command"
description = ""
type = "OrdIO"
io_file = "tests/10/io.txt"
io_prompt = "s*>\\s*$"
exp_exit_code = 0
argv = ["configs/dungeon_config_10.txt", "configs/story_config.txt"]
protected = false
env_vars = ['RAND_SEED=1234']

[[testcases]]
name = "inventory command"
description = ""
type = "OrdIO"
io_file = "tests/11/io.txt"
io_prompt = "s*>\\s*$"
exp_exit_code = 0
argv = ["configs/dungeon_config_11.txt", "configs/story_config.txt"]
protected = false
env_vars = ['RAND_SEED=1234']

[[testcases]]
name = "move command"
description = ""
type = "OrdIO"
io_file = "tests/12/io.txt"
io_prompt = "s*>\\s*$"
exp_exit_code = 0
argv = ["configs/dungeon_config_12.txt", "configs/story_config.txt"]
protected = false
env_vars = ['RAND_SEED=1234']

[[testcases]]
name = "loot command"
description = ""
type = "OrdIO"
io_file = "tests/13/io.txt"
io_prompt = "s*>\\s*$"
exp_exit_code = 0
argv = ["configs/dungeon_config_13.txt", "configs/story_config.txt"]
protected = false
env_vars = ['RAND_SEED=1234']

[[testcases]]
name = "use command"
description = ""
type = "OrdIO"
io_file = "tests/14/io.txt"
io_prompt = "s*>\\s*$"
exp_exit_code = 0
argv = ["configs/dungeon_config_14.txt", "configs/story_config.txt"]
protected = false
env_vars = ['RAND_SEED=1234']

[[testcases]]
name = "attack command"
description = ""
type = "OrdIO"
io_file = "tests/15/io.txt"
io_prompt = "s*>\\s*$"
exp_exit_code = 0
argv = ["configs/dungeon_config_15.txt", "configs/story_config.txt"]
protected = false
env_vars = ['RAND_SEED=1234']

[[testcases]]
name = "custom 1"
description = "testing start"
type = "OrdIO"
io_file = "tests/16/io.txt"
io_prompt = "s*>\\s*$"
exp_exit_code = 0
argv = ["configs/dungeon_config.txt", "configs/story_config.txt"]
protected = false
env_vars = ['RAND_SEED=1234']

[[testcases]]
name = "custom 2"
description = "normal start"
type = "OrdIO"
io_file = "tests/17/io.txt"
io_prompt = "s*>\\s*$"
exp_exit_code = 0
argv = ["configs/dungeon_config.txt", "configs/story_config.txt"]
protected = false
env_vars = ['RAND_SEED=1234']

[[testcases]]
name = "random generation"
description = "random numbers are 100% correct"
type = "OrdIO"
io_file = "tests/18/io.txt"
io_prompt = "s*>\\s*$"
exp_exit_code = 0
argv = ["configs/dungeon_config.txt", "configs/story_config.txt"]
protected = false
env_vars = ['RAND_SEED=1234']

[[testcases]]
name = "escape ending with casualties"
description = "..."
type = "OrdIO"
io_file = "tests/19/io.txt"
io_prompt = "s*>\\s*$"
exp_exit_code = 0
argv = ["configs/dungeon_config.txt", "configs/story_config.txt"]
protected = false
env_vars = ['RAND_SEED=1234']

[[testcases]]
name = "enemy phases"
description = "..."
type = "OrdIO"
io_file = "tests/20/io.txt"
io_prompt = "s*>\\s*$"
exp_exit_code = 0
argv = ["configs/dungeon_config_20.txt", "configs/story_config.txt"]
protected = false
env_vars = ['RAND_SEED=1234']

[[testcases]]
name = "simultaneous death"
description = "players and lich die at the same time"
type = "OrdIO"
io_file = "tests/21/io.txt"
io_prompt = "s*>\\s*$"
exp_exit_code = 0
argv = ["configs/dungeon_config_21.txt", "configs/story_config.txt"]
protected = false
env_vars = ['RAND_SEED=3435']

[[testcases]]
name = "Position command, use command"
description = ""
type = "OrdIO"
io_file = "tests/22/io.txt"
io_prompt = "s*>\\s*$"
exp_exit_code = 0
argv = ["configs/dungeon_config_20.txt", "configs/story_config.txt"]
protected = false
env_vars = ['RAND_SEED=3435']

[[testcases]]
name = "ammunition, placement"
description = ""
type = "OrdIO"
io_file = "tests/23/io.txt"
io_prompt = "s*>\\s*$"
exp_exit_code = 0
argv = ["configs/dungeon_config_23.txt", "configs/story_config.txt"]
protected = false
env_vars = ['RAND_SEED=1234']

[[testcases]]
name = "loot and move on player position"
description = ""
type = "OrdIO"
io_file = "tests/24/io.txt"
io_prompt = "s*>\\s*$"
exp_exit_code = 0
argv = ["configs/dungeon_config.txt", "configs/story_config.txt"]
protected = false
env_vars = ['RAND_SEED=1234']

[[testcases]]
name = "empty chest"
description = ""
type = "OrdIO"
io_file = "tests/25/io.txt"
io_prompt = "s*>\\s*$"
exp_exit_code = 0
argv = ["configs/dungeon_config_25.txt", "configs/story_config.txt"]
protected = false
env_vars = ['RAND_SEED=1234']

[[testcases]]
name = "wizard attacks with all weapons once"
description = ""
type = "OrdIO"
io_file = "tests/26/io.txt"
io_prompt = "s*>\\s*$"
exp_exit_code = 0
argv = ["configs/dungeon_config_26.txt", "configs/story_config_1.txt"]
protected = false
env_vars = ['RAND_SEED=1234']

[[testcases]]
name = "both config files invalid"
description = ""
type = "OrdIO"
io_file = "tests/27/io.txt"
io_prompt = "s*>\\s*$"
exp_exit_code = 3
argv = ["configs/dungeon_config_27.txt", "configs/story_config_2.txt"]
protected = false
env_vars = ['RAND_SEED=1234']

[[testcases]]
name = "order of error messages for move"
description = ""
type = "OrdIO"
io_file = "tests/28/io.txt"
io_prompt = "s*>\\s*$"
exp_exit_code = 0
argv = ["configs/dungeon_config.txt", "configs/story_config_1.txt"]
protected = false
env_vars = ['RAND_SEED=1234']

[[testcases]]
name = "order of error messages for everything"
description = ""
type = "OrdIO"
io_file = "tests/29/io.txt"
io_prompt = "s*>\\s*$"
exp_exit_code = 0
argv = ["configs/dungeon_config.txt", "configs/story_config_1.txt"]
protected = false
env_vars = ['RAND_SEED=1234']

[[testcases]]
name = "potion stuff"
description = ""
type = "OrdIO"
io_file = "tests/30/io.txt"
io_prompt = "s*>\\s*$"
exp_exit_code = 0
argv = ["configs/dungeon_config_30.txt", "configs/story_config_1.txt"]
protected = false
env_vars = ['RAND_SEED=2']

[[testcases]]
name = "unvalid or unavailable abbreivations"
description = ""
type = "OrdIO"
io_file = "tests/31/io.txt"
io_prompt = "s*>\\s*$"
exp_exit_code = 0
argv = ["configs/dungeon_config.txt", "configs/story_config_1.txt"]
protected = false
env_vars = ['RAND_SEED=1234']

[[testcases]]
name = "negative loot message"
description = ""
type = "OrdIO"
io_file = "tests/32/io.txt"
io_prompt = "s*>\\s*$"
exp_exit_code = 0
argv = ["configs/dungeon_config_25.txt", "configs/story_config_1.txt"]
protected = false
env_vars = ['RAND_SEED=1234']

[[testcases]]
name = "door to same room (don't know if this is even possible)"
description = ""
type = "OrdIO"
io_file = "tests/33/io.txt"
io_prompt = "s*>\\s*$"
exp_exit_code = 0
argv = ["configs/dungeon_config_33.txt", "configs/story_config_1.txt"]
protected = false
env_vars = ['RAND_SEED=1234']

[[testcases]]
name = "move out of bound"
description = ""
type = "OrdIO"
io_file = "tests/34/io.txt"
io_prompt = "s*>\\s*$"
exp_exit_code = 0
argv = ["configs/dungeon_config_34.txt", "configs/story_config.txt"]
protected = false
env_vars = ['RAND_SEED=1234']
